services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: inmatic
    container_name: inmatic
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    depends_on:
      - app
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inmatic
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmindb
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel-network
    ports:
      - "8585:80"
    depends_on:
      - db

networks:
  laravel-network:
    driver: bridge

volumes:
  dbdata:
